//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboration3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HasAbility
    {
        public int Ha_ID { get; set; }
        public int HasHero { get; set; }
        public int HasAbility1 { get; set; }
    
        public virtual Abilities Abilities { get; set; }
        public virtual Heroes Heroes { get; set; }
    }
}
