//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboration3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Heroes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Heroes()
        {
            this.HasAbility = new HashSet<HasAbility>();
        }
    
        public int Hero_Id { get; set; }
        [Required(ErrorMessage ="You must enter a name")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Must be at least 2 and max 20 charachters")]
        public string Hero_Name { get; set; }
        public int Hero_Class { get; set; }
        public string Hero_PortraitLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HasAbility> HasAbility { get; set; }
        public virtual HERO_CLASSES HERO_CLASSES { get; set; }
    }
}
