//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboration3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestEnteties : DbContext
    {
        public TestEnteties()
            : base("name=TestEnteties")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abilities> Abilities { get; set; }
        public virtual DbSet<ABILITY_TYPES> ABILITY_TYPES { get; set; }
        public virtual DbSet<HERO_CLASSES> HERO_CLASSES { get; set; }
        public virtual DbSet<Heroes> Heroes { get; set; }
    }
}
